version: 1
checks:
  severity: medium
  enable:
    - performance
    - readability
    - security
    - maintainability
ignore_paths:
  - node_modules/**
  - convex/_generated/**
  - .analysis_snapshot/**
notifications:
  pull_requests: true
  commits: false
