// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgkvrcsfvpknkemwerlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNna3ZyY3NmdnBrbmtlbXdlcmxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjM0NjcsImV4cCI6MjA3NDM5OTQ2N30.lOTMqEdx-L0Dhpy_ypN2qF5qk2R-ICwDJCRPturU26A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});